# Generated by Django 2.2.1 on 2019-05-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, verbose_name='Номер уголовного дела')),
                ('year', models.CharField(max_length=10, verbose_name='Год уголовного дела')),
                ('article', models.CharField(max_length=200, verbose_name='Уголовный кодекс - Статья')),
                ('organ', models.CharField(max_length=200, verbose_name='Возбудивший орган')),
                ('date_arousal', models.DateField(verbose_name='Дата возбуждение')),
                ('date_suspension', models.DateField(verbose_name='Дата приостановления')),
                ('criminals', models.ManyToManyField(blank=True, to='persons.Criminals', verbose_name='Люди проходящие по делу')),
            ],
            options={
                'verbose_name': 'Уголовное дело',
                'verbose_name_plural': 'Уголовные дела',
                'ordering': ['year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Manhunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_case_number', models.CharField(max_length=200, verbose_name='Номер розыскного дело')),
                ('date_arousal', models.DateField(verbose_name='Дата заведения розыскногот дела')),
                ('invest_initiator', models.CharField(max_length=200, verbose_name='Инициатор заведивщий дело')),
                ('invest_category', models.CharField(max_length=200, verbose_name='Категория учета розыска')),
                ('circular_number', models.CharField(max_length=200, verbose_name='Номер циркуляра')),
                ('preventive', models.CharField(max_length=200, verbose_name='Мера пресечения')),
                ('date_inter_invest', models.DateField(blank=True, null=True, verbose_name='Дата поступления в международный розыск')),
                ('invest_stopped', models.BooleanField(verbose_name='Розыск прекращен')),
                ('place_detention', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место задержания')),
                ('date_detention', models.DateField(blank=True, null=True, verbose_name='Дата задержания')),
                ('invest_stopped_circular', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер циркуляра о прекращении розыска')),
                ('criminalCase_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='law.CriminalCase', verbose_name='Номмер уголовного дело')),
                ('criminal_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.Criminals', verbose_name='Человек в розыске')),
            ],
            options={
                'verbose_name': 'Розыскное дело',
                'verbose_name_plural': 'Розыскные дела',
                'ordering': ['criminal_id'],
            },
        ),
        migrations.CreateModel(
            name='Conviction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_case_number', models.CharField(max_length=200, verbose_name='Номер уголовного дело')),
                ('criminal_case_year', models.CharField(max_length=10, verbose_name='Год уголовного дело')),
                ('criminal_case_organ', models.CharField(max_length=200, verbose_name='Орган возбудивщий угоовного дело')),
                ('law_article', models.CharField(max_length=200, verbose_name='Статья УК')),
                ('date_sentence', models.DateField(verbose_name='Дата приговора')),
                ('date_release', models.DateField(verbose_name='Дата освобождения')),
                ('criminal_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.Criminals', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Судимость',
                'verbose_name_plural': 'Судимости',
                'ordering': ['criminal_id'],
            },
        ),
        migrations.CreateModel(
            name='Confluence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres', models.CharField(choices=[('V', 'Выезд'), ('Z', 'Въезд')], default='V', max_length=1, verbose_name='Выезд/въезд')),
                ('kind', models.CharField(max_length=200, verbose_name='Вид пересечение')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('criminal_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.Criminals', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Пересечение',
                'verbose_name_plural': 'Таблица пересечений',
                'ordering': ['criminal_id'],
            },
        ),
    ]
