# Generated by Django 2.2.1 on 2019-05-17 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20190516_1620'),
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalcase',
            name='criminals',
        ),
        migrations.AddField(
            model_name='criminalcase',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='conviction',
            name='criminal_case_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='law.CriminalCase', verbose_name='Номер уголовного дело'),
        ),
        migrations.AlterField(
            model_name='criminalcase',
            name='date_arousal',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возбуждение'),
        ),
        migrations.AlterField(
            model_name='criminalcase',
            name='date_suspension',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приостановления'),
        ),
        migrations.CreateModel(
            name='CriminalCaseCriminals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law.CriminalCase', verbose_name='Уголовное дело')),
                ('criminal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Criminals', verbose_name='Люди проходящие по делу')),
            ],
            options={
                'verbose_name': 'Уголовное дело -- ответчики',
                'verbose_name_plural': 'Уголовное дело -- ответчики',
            },
        ),
    ]
