# Generated by Django 2.2.1 on 2019-05-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0002_auto_20190517_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manhunt',
            name='invest_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Категория учета розыска'),
        ),
    ]
