# Generated by Django 2.2.1 on 2019-05-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0003_auto_20190517_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manhunt',
            name='circular_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер циркуляра'),
        ),
        migrations.AlterField(
            model_name='manhunt',
            name='date_arousal',
            field=models.DateField(verbose_name='Дата заведения розыскного дела'),
        ),
    ]
