# Generated by Django 2.2.1 on 2019-05-11 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=40, verbose_name='Тип пользователя')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Таблица ролей',
            },
        ),
        migrations.CreateModel(
            name='TrustLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_level', models.CharField(max_length=200, verbose_name='Уровень доверия/конфиденциальность')),
                ('level', models.IntegerField(verbose_name='Уровень')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role', verbose_name='Роль пользователя')),
                ('trust_level_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.TrustLevel', verbose_name='Уровень доверия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
