# Generated by Django 2.2.1 on 2019-05-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190511_1702'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalsContactPersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Контактируемое лицо',
                'verbose_name_plural': 'Контактируемые лица',
            },
        ),
        migrations.CreateModel(
            name='CriminalsRelatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Родственники',
                'verbose_name_plural': 'Родственники',
            },
        ),
        migrations.RemoveField(
            model_name='criminals',
            name='health_information',
        ),
        migrations.RemoveField(
            model_name='criminals',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='criminals',
            name='job',
        ),
        migrations.RemoveField(
            model_name='criminals',
            name='level',
        ),
        migrations.RemoveField(
            model_name='criminals',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='criminals',
            name='workplace',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='health_information',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='level',
        ),
        migrations.AddField(
            model_name='criminals',
            name='close',
            field=models.BooleanField(default=False, verbose_name='Закрыть доступ'),
        ),
        migrations.AddField(
            model_name='criminals',
            name='confident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.TrustLevel', verbose_name='Уровень секретности'),
        ),
        migrations.AddField(
            model_name='criminals',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.Organizations', verbose_name='Организации'),
        ),
        migrations.AddField(
            model_name='criminals',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Owner', to='users.Profile', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='criminaladdresses',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='criminaladdresses',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.Region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='criminaladdresses',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='education_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место образование'),
        ),
        migrations.RemoveField(
            model_name='criminals',
            name='occupation',
        ),
        migrations.AddField(
            model_name='criminals',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.Occupation', verbose_name='Деятелльность'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='user',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile', verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='foundation_year',
            field=models.CharField(blank=True, default='Неизвестно', max_length=20, null=True, verbose_name='Год основание'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='ideology',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Идеология организации'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='leader',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Лидер организации'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.Occupation', verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birth_City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birth_District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birth_Village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.Village', verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birth_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.Region', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождение'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='citizenship',
            field=models.CharField(blank=True, default='Не указан', max_length=200, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='education_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место образование'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='issue_data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='issue_organ',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место выдачи'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='job',
            field=models.CharField(blank=True, default='Не указан', max_length=200, null=True, verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='passport_number',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='passport_serial',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='patronymic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчетство'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='user',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='users.Profile', verbose_name='Создал'),
        ),
        migrations.DeleteModel(
            name='CriminalsActivity',
        ),
        migrations.AddField(
            model_name='criminalsrelatives',
            name='criminal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Criminals'),
        ),
        migrations.AddField(
            model_name='criminalsrelatives',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Persons'),
        ),
        migrations.AddField(
            model_name='criminalsrelatives',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.RelativeRelation'),
        ),
        migrations.AddField(
            model_name='criminalscontactpersons',
            name='criminal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Criminals'),
        ),
        migrations.AddField(
            model_name='criminalscontactpersons',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Persons'),
        ),
        migrations.AddField(
            model_name='criminalscontactpersons',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.RelativeRelation'),
        ),
    ]
