# Generated by Django 2.2.1 on 2019-05-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20190512_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminals',
            name='birth_City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='birth_District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='birth_Village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.Village', verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='birth_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.Country', verbose_name='Страна рождения'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='birth_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.Region', verbose_name='Область'),
        ),
    ]
