# Generated by Django 2.2.1 on 2019-05-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20190512_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaladdresses',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='criminaladdresses',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='criminaladdresses',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='criminaladdresses',
            name='village',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='birth_City',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='birth_District',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='birth_Village',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='birth_country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна рождения'),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='birth_region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='personaddresses',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='personaddresses',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='personaddresses',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='personaddresses',
            name='village',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birth_City',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birth_District',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birth_Village',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birth_country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна рождения'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birth_region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Область'),
        ),
    ]
