# Generated by Django 2.2.1 on 2019-05-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_criminals_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relativerelation',
            options={'ordering': ['type'], 'verbose_name': 'Вид связи', 'verbose_name_plural': 'Виды связей'},
        ),
        migrations.RemoveField(
            model_name='contactrelation',
            name='relative',
        ),
        migrations.RemoveField(
            model_name='relativerelation',
            name='relative',
        ),
    ]
