# Generated by Django 2.2.1 on 2019-05-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20190516_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='criminaladdresses',
            name='date_entry',
            field=models.DateField(blank=True, null=True, verbose_name='Дата входа'),
        ),
        migrations.AlterField(
            model_name='criminaladdresses',
            name='date_release',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода'),
        ),
    ]
