# Generated by Django 2.2.1 on 2019-05-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20190516_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalscontactpersons',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.ContactRelation'),
        ),
    ]
